# Generated by Django 2.0 on 2018-04-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='grupo',
            new_name='grupos',
        ),
    ]
