# Generated by Django 2.0 on 2018-04-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20180420_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='grupos',
        ),
        migrations.AddField(
            model_name='tarea',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Grupo', to='tareas.Grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
